import gradio as gr
import tensorflow as tf
from PIL import Image
import numpy as np

# Load your MobileNetV2 model
model = tf.keras.models.load_model('mobilenetv2_cifake.keras')

def predict_image(img):
    # Preprocess the image to match your model's input
    img = img.resize((32, 32)) # Assuming 32x32 based on CIFAKE
    img_array = np.array(img) / 255.0
    img_array = np.expand_dims(img_array, axis=0)
    
    # Make prediction
    prediction = model.predict(img_array)[0][0]
    
    # Return results as a dictionary for Gradio
    # Assuming 0 is Real and 1 is Fake (swap if your model is different!)
    if prediction > 0.5:
        return {"Fake (AI-Generated)": float(prediction), "Real (Photograph)": float(1 - prediction)}
    else:
        return {"Real (Photograph)": float(1 - prediction), "Fake (AI-Generated)": float(prediction)}

# Create the Gradio interface
interface = gr.Interface(
    fn=predict_image,
    inputs=gr.Image(type="pill"),
    outputs=gr.Label(num_top_classes=2),
    title="🕵️‍♂️ SynthCatch: AI Image Detector",
    description="Upload an image to see if it was generated by AI or if it's a real photograph."
)

if __name__ == "__main__":
    interface.launch()